version: "3"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy

    container_name: wg-easy

    restart: unless-stopped

    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"

    volumes:
      - ./config:/etc/wireguard

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
